# Configuration Pre-commit pour EMANET VOXTRAL B200
# Version simplifiée et fonctionnelle

repos:
  # Hooks standards pre-commit
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        name: "Supprime espaces en fin de ligne"
      - id: end-of-file-fixer
        name: "Assure fin de fichier"
      - id: check-yaml
        name: "Vérifie syntaxe YAML"
      - id: check-toml
        name: "Vérifie syntaxe TOML"
      - id: check-json
        name: "Vérifie syntaxe JSON"
      - id: check-added-large-files
        name: "Détecte gros fichiers"
        args: ['--maxkb=10000']
      - id: check-merge-conflict
        name: "Détecte conflits merge"
      - id: debug-statements
        name: "Détecte debug statements"

  # Formatage code Python
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        name: "black - formatage Python"
        language_version: python3

  # Tri imports
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: "isort - tri imports"
        args: ["--profile", "black"]

  # Linting Python
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        name: "flake8 - linting Python"
        exclude: ^tests/

  # Analyse sécurité
  - repo: https://github.com/pycqa/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        name: "bandit - analyse sécurité Python"
        args: ["-c", "pyproject.toml"]
        exclude: ^tests/